services:
  - type: web
    name: ai-image-classifier
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      PYTHON_VERSION: 3.11.0
